import AboutSection from "@/component/about";
import Banner from "@/component/banner";
import Connection from "@/component/connection";
import Counter from "@/component/counter";
import Courses from "@/component/courses";
import CourseSection from "@/component/courseSection";
import Herosection from "@/component/heroSection";
import Services from "@/component/services";
import Testimonial from "@/component/testimonial";
import Training from "@/component/training";
import { Box } from "@mui/material";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Edzu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Box>
        {/* <Banner /> */}
        <Herosection />
        <CourseSection />
        <Box sx={{ pt: 8, pb: 8 }}>
          <Courses />
        </Box>
        <Box sx={{ pt: 8, pb: 8 }}>
          <AboutSection />
        </Box>
        <Box sx={{ pt: 8, pb: 8 }}>
          <Counter />
        </Box>
        <Box sx={{ pt: 8, pb: 8 }}>
          <Testimonial />
        </Box>
        <Box sx={{ pt: 8, pb: 8 }}>
          <Connection />
        </Box>
        <Box sx={{ pt: 8, pb: 8 }}>
          {/* <Training /> */}
          <Services />
        </Box>
      </Box>
    </>
  );
}
